services:
  debtors-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debtors-api
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    networks:
      - app-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue-worker
    volumes:
      - .:/var/www/html
    depends_on:
      - debtors-api
      - mongodb
      - redis
    env_file:
      - .env
    command: ["sh", "-c", "./wait_for_mongo.sh"]
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
